name: game2048

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the actions tab
  # workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      
      - name: cache
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      
      - name: build
        run: |
          mvn compile
          mkdir staging && cp -r target/* staging
          
      - name: archive
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: staging
          retention-days: 7
          
  test:
    needs: build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      
      - name: cache
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
          
      - name: test
        run: |
          mvn test
          mkdir staging && mkdir staging/surefire-reports && cp -r target/surefire-reports/* staging/surefire-reports
          mkdir staging/jacoco && cp -r target/site/jacoco/* staging/jacoco
          
      - name: archive
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: staging
          retention-days: 7
          
  analyze:
    needs: test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      
      - name: cache
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
          
      - name: analyze
        continue-on-error: true
        run: mvn sonar:sonar -Dsonar.projectKey=g2048 -Dsonar.host.url=localhost:9000 -Dsonar.login=a7368dada0a5bbdc46cee5c8be575ae4faab5491
